### ISSUE TITLE
Text in dropdown menu is two different sizes

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1680] opened 2019-07-05 21:48 UTC
Likely caused by one being a link and one a button.

<img width="248" alt="Screen Shot 2019-07-05 at 3 47 23 PM" src="https://user-images.githubusercontent.com/509309/60746509-3f474400-9f3c-11e9-97b8-dd6588f6e618.png">

### This task is done when...
 - [ ] Text is the same size

**Comment by mgwalker** [comment] 2019-07-23 14:46
Duplicate of #1655

**Closed by mgwalker** 2019-07-23 14:46 UTC
Labels: Sev3, bug
