### ISSUE TITLE
Change password button switches email

### ISSUE THREAD

**Issue by pphillips-fearless** [18F/cms-hitech-apd#2212] opened 2020-05-07 15:33 UTC
When logged in as an admin, if you try to change the password of another user, when you click the "change password" button the user's email address is switched to the current user's email address (after a 1 second lag).  So then if you click the submit button you see an error message saying "Another account already exists with that email address"

![image.png](https://images.zenhubusercontent.com/5e6a4b048168d5a15258c7d1/fc5ed6fa-722c-4f4f-be71-6698452e781b)

### This task is done when...
 - [ ] the "change password" button doesn't switch the email address

**Comment by mgwalker** [comment] 2020-05-26 18:49
I can't reproduce this, but it's got me wondering if there's a login autofill issue happening. When you click the "change password" button and the password field becomes visible, I wonder if the browser's autofill recognizes it and tries to fill in your info. That doesn't seem super likely, though, because it didn't fill in the password field... 🤔 

I'll keep playing with it and see if I can get it to happen.

**Comment by pphillips-fearless** [comment] 2020-05-27 15:05
I did a test where I disabled my lastpass browser extension and tried to reproduce it and it acted correctly.  Then I turned lasspass back on and was able to recreate the issue.  So that confirms your hypothesis @mgwalker, that it was caused by the browser autofill.

**Comment by mgwalker** [comment] 2020-05-27 20:32
LastPass will ignore non-password fields that have `search` somewhere in the ID or name attributes. I'm not super keen to change our form element IDs or names to satisfy a single password manager, especially if it only works for non-password fields, but I'll leave that up to @jeromeleecms. I think I'd probably suggest closing this one.

The only other option is adding a `data-lpignore` attribute to the form elements. That only works if the LastPass user has enabled that feature, and it's disabled by default. So I wouldn't expect that to accomplish much in practice.

**Comment by nicholeweems** [comment] 2020-05-28 17:06
@jeromeleecms concurs with the @mgwalker feedback and suggestion and agrees to close the issue.

**Closed** 2020-05-28 17:07 UTC
Labels: Small, bug, development
