### ISSUE TITLE
Implement executive summary section

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#612] opened 2018-05-25 15:11 UTC
Dev implementation of executive summary section.

### This task is done when...
 - [ ] Develop a submission experience
 - [ ] Design reviews upon implementation

**Comment by mgwalker** [comment] 2018-05-29 15:43
This one is pending #606, right?  Or is that design done?

**Comment by brendansudol** [comment] 2018-05-31 15:49
can you advise here @quarterback?

**Comment by NAretakis** [comment] 2018-05-31 18:13
Sorry, we have some overlap. This is a duplicate of #626

**Closed** 2018-05-31 18:14 UTC
Labels: development
