### ISSUE TITLE
Saving the APD is not working (though system reports a successful save)

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1226] opened 2019-01-10 22:14 UTC
Updating an APD and saving the changes is not working. Updated project staff, activities, and some additional fields, but after receiving a successful save notification, backing out and coming back into the APD shows none of the data has been saved.

### This task is done when...
 - [ ] Identify why a successful save notification is being reported
 - [ ] Notification information is accurately reported and/or saves are correctly being done in the database

**Comment by mgwalker** [comment] 2019-01-22 22:21
Once everything is back up and running, can we try this one again?  I'm not able to reproduce it right now, but this is a Big Deal™ so let's check it a lot.  😄

**Comment by jeromeleecms** [comment] 2019-01-23 20:55
@mgwalker Let me know when you want me to retest. Now that the app is back and running, I created a new APD, filled in a single field, and selected save. System reported "Save Successful," but when I looped back to the dashboard, back into the APD, the field was blank again.

**Comment by mgwalker** [comment] 2019-01-23 22:23
Oh!  I see.  I can reproduce that.

If you reload the page in the browser and then open your APD, does the data come back?  If so, I'm pretty sure I know where the problem is.

**Comment by mgwalker** [comment] 2019-01-23 22:50
Here's how the data flow currently goes:

1. When you load the site, we send a `GET /apds` request to the API.  This returns all of the APDs for the user's state.  This is stored in the application state at the `apds.byId` location.
2. When you select an APD on the site, we *copy* the APD data for the selected APD from `apds.byId` to `apds.data`.
3. As you edit the APD, we update `apds.data`.
4. You press save and the data from `apds.data` is uploaded to the API and saved in the database.
5. When you click back to the dashboard and select your APD again, we again copy from `apds.byId`, which was never updated.  This creates the appearance that all your saved changes were lost.  If you save the APD now, they really will be lost.

---

Proposed fix:

1. When you load the site, we send a `GET /apds` request to the API.  This returns basic metadata about all of the APD's for the user's state, but not ALL of the APD data.  This is stored in the application state at the `apds.byId` location.
2. When you select an APD on the site, we send a `GET /apds/:id` request to the API.  This returns the full data for the selected APD.  We store that at the `apds.data` location.
3. As you edit the APD, we update `apds.data`.
4. You press save and the data from `apds.data` is uploaded to the API and saved in the database.
5. When you click back to the dashboard and select your APD again, we fetch it from the API again.

This way, every time you select an APD, you are getting the most recent version from the database.

---

We need to make sure we understand everywhere that `apds.byId` is being used and what data needs to be there.

**Comment by mgwalker** [comment] 2019-01-24 00:55
Yes, app system already tracks that, in fact!  Part of the app state is the `dirty` section, which has a boolean indicating if anything has changed, and then a structured object tracking which sections in particular have been changed.  We use it to make saves a little more efficient by only sending the parts that have been edited.

**Comment by jeromeleecms** [comment] 2019-01-24 15:47
Great -- created #1237 added to document that as a future enhancement. 

Just for clarity, when the user saves the APD, does the `dirty` boolean switch back to false?

**Comment by mgwalker** [comment] 2019-01-24 16:07
Yes  :)

**Comment by mgwalker** [comment] 2019-02-07 15:28
Should be fixed by #1238.  @jeromeleecms Care to test it out?  :)

**Comment by jeromeleecms** [comment] 2019-02-07 15:53
Confirmed @mgwalker  - Bug squashed! 👏

**Closed** 2019-02-07 15:54 UTC
Labels: bug
