### ISSUE TITLE
User Login without Name Field Doesn't allow user to login

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#2046] opened 2020-02-04 19:10 UTC
Found a strange situation yesterday when trying to reset a user's password. The account only had the user's email address with no name in the [name] field.

Tried:
1. Updated the password, saved, and still couldn't login. 
2. Fail
3. Added name and updated the password (same password) 
4. Success!

### This task is done when...
 - [ ] Understand why this happened
 - [ ] Decide what we should do about this (fix or leave as is)

**Comment by mgwalker** [comment] 2020-02-05 16:22
I can't reproduce this in dev. When you entered the password, did you type it by hand or did you copy/paste it? Did the user hand-type or copy/paste? I'm curious if there's a situation where the wrong password got entered in either step 1 or 2.

If everyone was copy-pasting, we'll need to dig into this some more.

**Comment by jeromeleecms** [comment] 2020-02-05 16:42
I typed it and verified using "Show Password." 

If we can't verify, I'm OK with closing this as an isolated incident and opening a new issue if we encounter this at a future date.

Thoughts?

**Comment by mgwalker** [comment] 2020-02-11 18:11
Closing as cannot reproduce

**Closed by mgwalker** 2020-02-11 18:11 UTC
Labels: bug
