### ISSUE TITLE
Investigate replacing the rich text editor

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1127] opened 2018-11-15 16:32 UTC
The rich text editor component we use - [react-draft-wysiwyg](https://github.com/jpuri/react-draft-wysiwyg) - appears like it may have been abandoned by its maintainer.  Unfortunately, it has a pretty significant performance problem in the way it handles events.  It's a fairly simple fix, but we have no guarantee the author would make the fix/accept our fixes (especially if they've decided to leave this project to do other things).

I don't have a proposal for the path forward, but here are some options to get a conversation started:

* Do nothing and accept the performance penalty.  The larger the APD, the worse the penalty will be.
* Try to engineer a solution on our side where we forcibly destroy the rich text editors that aren't visible.  That could mitigate some of the performance problems.
  - However, performance would degrade as more rich text editors were shown, so if the user opens a lot of sections, the page would slow down
* Make the fixes and submit them to the author and hope they accept them.
* Make the fixes and use our fixed version of the component.
  - This introduces something new to maintain, which we probably don't really want.  Might be okay as a stopgap, or if we had a good reason to believe the author would eventually come back.
* Switch to a different library, such as using [draft.js](https://draftjs.org/) directly (maintained by Facebook, just like React, so probably not going away any time soon)
  - Might not be able to find anything with perfect feature parity
  - Might be complicated to retrofit (I don't *think* so, but 🤷‍♂️)

Aside from the poor performance in the app, this doesn't feel like a particularly high priority.  The editor we have now functions fine, it's just slowing everything down.

### This task is done when...
 - [x] there's a decision

**Comment by mgwalker** [comment] 2018-11-16 21:40
I sent the react-draft-wysiwyg maintainer an email to ask if she's still tending to the project.  If she is, then I'd be more interested in getting our fixes upstream.  If she's not, then I'd be more interested in finding something else to use.  Just FYI.  I'll update here if I hear back from her!

**Comment by mgwalker** [comment] 2019-01-23 14:59
From the author:

>I am happy that you liked the editor. It is one of the most popular editors in DraftJS. Due to some other priorities I am not putting time into it atm. But plz let me know in case you need any help with the editor, I will be happy to do that.

So here are the options that I see:

1. do nothing and accept the performance penalty; the more activities in an APD, the worse the penalty
   - **pros:** easy - don't do anything!
   - **cons:** everything is still slow ☹️ 
2. fork react-draft-wysiwyg, fix it, and use our version
   - **pros:** we know how to fix it, and it's not a ton of work
   - **cons:** something else we have to maintain
   - if the author comes back, we'd probably want to submit an upstream fix and switch back - something to keep track of
3. switch to a different rich text editor library
   - **pros:** can pick something that is actively maintained
   - **cons:** might not find something with all the same features
   - might be complicated to retrofit

Whenever this is prioritized, my recommendation would be a research spike around option 3 to see what's out there, what features we'd lose/gain, and the effort to replace it.  The result of that spike could inform a decision.

Of course, if we choose option 1, this issue is complete.  😜

**Comment by hbillings** [comment] 2019-01-28 16:26
A research spike around #3 is also my vote, with #2 being a backup. (If we went with #2, we could always do #3 if it appears the project is dead.)

**Comment by NAretakis** [comment] 2019-01-29 21:06
Agree on #3, and we'll maybe just have to figure out when we spike on this, in conjunction with road-map & time-frames.

**Comment by jeromeleecms** [comment] 2019-01-29 23:21
From a philosophical standpoint, are paid solutions on the table for the research spike? CKeditor and TinyMCE are paid solutions with react components that seem to support direct copy and paste from Word (which was a recurring request during user testing). Not sure about the performance of either library, but wanted to define what was inbounds and out of bounds.

Also, I agree that this is a not a huge priority. @mgwalker At what # of activities are you thinking the performance will be untenable? HITECH APDs generally contain a small number of activities for a large number of our states, so performance may not be so critical. 

#3 sounds good, but we should combine that with some research about how many activities are actually being submitted (is that greater than the limit for poor performance?). Most diversity of activities appear in the HIE space, but even then, for a lot of states, the number of activities is limited.

If we are able to expand the app down the road, it would be interesting to see how it affected state's submission behavior. Would they want to/decide to combine their entire IT portfolio into a single APD submission (potentially lots of activities), keep them separate (few activities), or submit more focused APDs (even fewer activities)? In the latter two cases, then performance concerns are less critical and we can stick with #1...

Just a "few" thoughts :)

**Comment by mgwalker** [comment] 2019-01-30 00:41
I think paid options are on the table if y'all want to consider them. 😉  Some food for thought on them, though:

- both CKEditor and TinyMCE rely on their own SaaS, so they'd need to be ATOed *separately* before they could be incorporated into the app (TinyMCE has an option for you to host the backend yourself, which would add another dependency to maintain but that might be easier than getting a SaaS through ATO)
- make sure you have a plan for what happens if a payment is missed/late
- be aware they can be logistically challenging in development - they require the use of API keys that are tied to a domain address, so they won't work in a development environment (TinyMCE supports working without an API key for development mode, which is nice; it introduces a small build complexity in that you need to inject the API key depending on your environment)

All of those are manageable, but just wanted to raise that they're not quite as simple to integrate as an open source library.

I really like this question about performance as a function of activities, and researching how users are building their APDs.  When/if the time comes to address this, that sounds like a great way to do it.

FWIW, performance falls off pretty quickly.  In general, we want the UI to respond to a human interaction within about 200 ms.  That's about where it becomes perceptible and thus a nuisance. After around 400 ms, I think that's when it starts to frustrate people.  Just a quick look at my test APD with 6 activities, it's about a 400 ms delay on any click.  With one activity, it seems to be around 50 ms.  (Which will vary with browser and computer specs...  we should test this in IE...).  The big problem here is how often that delay gets triggered - every click, every key press, etc.  I think I can build a quick test app that does performance metrics with different numbers of editors in a couple of hours.  Would that be worth the effort so we'll have that information?

**Comment by jeromeleecms** [comment] 2019-01-30 16:10
Very insightful - thank you! Six seems like a pretty small number, so seems this is worth discussing during our "Fingers off the keyboard" discussion or during sprint planning.

In some of the design discussions, we've gone back and forth about splitting the app into multiple pages because of how lengthy the content becomes. Would that potentially help performance? We could include this in the research about the app/user experience, esp. since there is no guarantee that a new library wouldn't suffer the same performance concerns...

**Comment by hbillings** [comment] 2019-01-30 16:57
I think if we decide the research spike is too time consuming, we should go with option #2 (since this behavior is caused by a bug and we know how to fix said bug) rather than optimize the app for the performance drag. :)

**Comment by jeromeleecms** [comment] 2019-04-01 20:41
We are going with #2!

**Comment by NAretakis** [comment] 2019-04-16 14:19
Closing this issue, and opened #1466 for dev implementation. Yay to process!

**Closed by NAretakis** 2019-04-16 14:19 UTC
