### ISSUE TITLE
Remove white space from "consent to monitoring" screen

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1603] opened 2019-06-12 20:13 UTC
### This task is done when...
 - [ ] white space is removed from "consent to monitoring" page
  - The margin-top on the footer is causing the white space, but there might be some weirdness around the footer not being anchored to the bottom.

Before
<img width="1105" alt="Screen Shot 2019-06-12 at 3 49 42 PM" src="https://user-images.githubusercontent.com/23194720/59382770-76a34600-8d2c-11e9-89dd-74cec8a48cfc.png">

After
<img width="1100" alt="Screen Shot 2019-06-12 at 4 12 29 PM" src="https://user-images.githubusercontent.com/23194720/59382971-fdf0b980-8d2c-11e9-859b-979447d4ed03.png">

**Comment by hbillings** [comment] 2019-07-22 20:46
More or less a duplicate of #1572.

**Closed by hbillings** 2019-07-22 20:46 UTC
Labels: Sev3, bug
