### ISSUE TITLE
Don't show date errors before the user actually enters a date

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1738] opened 2019-07-31 17:48 UTC
Right now, the date field shows error messages on a brand new APD for blank dates. Instead, hide those errors until the user has made a change to the date.

### This task is done when...
 - [ ] date errors are not shown on a new APD
 - [ ] errors only show up after the user has made a change to the date

**Comment by mgwalker** [comment] 2019-07-31 19:01
Possibly an easy way to handle this is to make empty dates valid. Since saves will succeed as long as the date is either valid or `null`, we can update the component to return `null` for dates that are empty strings.  Then saves will succeed, and empty dates should be considered valid.

**Comment by jeromeleecms** [comment] 2019-08-05 18:37
Duplicate of #1742

**Closed by jeromeleecms** 2019-08-05 18:37 UTC
Labels: Sev3, bug, development
