### ISSUE TITLE
Display some kind of loading progress indicator when opening an APD

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1918] opened 2019-11-12 20:22 UTC
When you click an APD, it takes a few seconds to load. Rather than just have an unresponsive page that doesn't indicate anything has happened, we should show some kind of indicator.

### This task is done when...
 - [ ] we know what to show
 - [ ] we show it

**Comment by jeromeleecms** [comment] 2019-11-12 20:39
Duplicate of #1368.

**Closed by jeromeleecms** 2019-11-12 20:39 UTC
Labels: design, development
