### ISSUE TITLE
Log In error banner doesn't announce itself to screen readers

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1678] opened 2019-07-05 21:14 UTC
If a user enters incorrect login info, the alert banner at the top of the screen does not get announced to the user, so there is no indication of an incorrect login attempt.

### This task is done when...
 - [ ] Alert banner is read on login fail
 - [ ] Probably needs a `role=alert` and/or `aria-live=assertive`

**Comment by NAretakis** [comment] 2019-07-08 20:20
duplicate of #1303, closing issue.

**Closed by NAretakis** 2019-07-08 20:20 UTC
Labels: accessibility, development
