### ISSUE TITLE
[Duplicate] Use formatting in YAML to break up long helptext sections

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#1018] opened 2018-09-12 15:08 UTC
YAML file supports spacing and (in theory) HTML, so can experiment with formatting sections to break up long help text.

### This task is done when...
 - [ ] Make sure formatting in YAML works by experimenting to break up long help text sections.
 - [ ] If it works, implement globally. (If not, spin up a separate dev issue.)
 - [ ] Product reviews the experience.

**Comment by quarterback** [comment] 2018-09-12 17:43
@jameshupp we can talk about this before you dive in, if you want to and I can provide additional context. Just focusing on better spacing the content where there is long text. It occurs to me there's no real documentation to the yaml file...probably something I should try to do.

**Comment by jeromeleecms** [comment] 2018-10-04 16:32
Duplicate of #1034.

**Closed by jeromeleecms** 2018-10-04 16:32 UTC
Labels: content
