### ISSUE TITLE
In the exported PDF, budget tables need to be formatted so they're entirely visible

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1262] opened 2019-02-05 17:58 UTC
Currently, budget tables are horizontally truncated on the web app and can be scrolled.  When they're exported to PDF, however, they need to be wholly visible at once since paper doesn't have internal scrolling.

### This task is done when...
 - [ ] budget tables are visible in their entirety in the exported PDF

**Comment by hbillings** [comment] 2019-03-05 18:02
One solution would be to reformat tables so that there is less data spread horizontally and more data spread vertically. Here's an example of what I mean:

<img width="478" alt="screen shot 2019-03-05 at 11 00 49 am" src="https://user-images.githubusercontent.com/509309/53826514-fce20c00-3f35-11e9-9337-797c61ae9fcb.png">

That said, I don't know if there's user research that shows that this is a less intuitive way to format this data. This is also sort of a heavy lift. @jenniferthibault and @lauraponce, I would love input on this.

**Comment by lauraponce** [comment] 2019-03-05 18:23
It seems like the idea here is just to stack the tables vertically instead of side by side? To me, that seems like a solid solution for the pilot (and maybe we could look into some fancier table layouts for layer 2+ post pilot). 

If the tables become two separate components rather than one longer vertical table, it might help orient users to add in the column headers for the second table as well.

The only research we have around the tables is that the horizontal tables are difficult to use since it's unnatural to scroll that way. So anything that's veering away from that is a step in the right direction and can be backed up with the research.

I can't quite tell from this screenshot what the gray bar in the middle of the tables is since it's cut off, is that a leftover scrollbar from the horizontal tables?

**Comment by hbillings** [comment] 2019-03-06 00:04
Yep, you're exactly right. Good call on adding the headers to the second table too! And I really appreciate the research insight.

The gray bar is the page break in the PDF (which makes it even more important to have headers on that second table, since it's not even on the same page in this case.

**Comment by hbillings** [comment] 2019-03-06 00:05
@NAretakis @jeromeleecms I'd be interested in feedback from the two of you, also! (Forgot to tag you originally, whoops!)

**Comment by jameshupp** [comment] 2019-03-06 00:15
I understand this vertical (time) and horizontal (type of data) arrangement, but it feels more intuitive to me the other way. Would it be reasonable to do it like this?

1. Split the tables just like this.
2. Keep the Quarters vs EH/EP directions the same as before, with annual totals at the end of the row.
3. Render the multi-year totals separately in its own little div so it doesn't look like part of a table at all. Maybe the word **Totals** and then a little 2x2? It'd also serve to highlight that part even more strongly.

I could draw the concept on a napkin if that's helpful. :) But if breaking the vert/horiz arrangement for the annual totals is just going to be extra confusing, I like the concept above.

**Comment by NAretakis** [comment] 2019-03-06 07:01
I think splitting and stacking the tables will give us better use of the screen real estate and removing the scrolly-ness inside the app would be a ➕!

That said, I like what @jameshupp said about swapping the X/Y axis around (keeping it axis's the same as how it is currently in the app). The table as we currently have it, is actually modeled on how a few states constructed the tables in their paper versions, so, keeping _quarters_ on the X-axis would give a consistent feel. 

Additionally, if we keep quarters on the x-axis and also keep _subtotal_ I am 100% fine with us simply removing the "grand total" columns. "Grand total" is actually a nice to have, but not a must have.

**Comment by jenniferthibault** [comment] 2019-03-06 20:20
We definitely have precedent for unstacking tables, and indeed had started to do so in https://github.com/18F/cms-hitech-apd/issues/1111 !! 🎉 

It seems like a visualization of Nick & James' suggestion above would be helpful to make sure we're all on the same page. I'm starting a mockup right now!

**Comment by jenniferthibault** [comment] 2019-03-06 20:49
Like so?
![screen shot 2019-03-06 at 3 48 51 pm](https://user-images.githubusercontent.com/11636908/53912646-642bb900-4027-11e9-8c59-297552a9be50.png)

**Comment by jeromeleecms** [comment] 2019-03-06 21:18
I think that looks good - nice to see people's thoughts in pictures!

The only place I might have some hesitation about applying this heuristic is in the program budget tables in the executive summary (which was intended to mirror the approval letter table):

Screenshot from the fake APD app data: 
![image](https://user-images.githubusercontent.com/34279968/53913221-b4971c80-400f-11e9-986c-e763da6ee946.png)

![image](https://user-images.githubusercontent.com/34279968/53913336-fa53e500-400f-11e9-898d-7eb20679ef19.png)

I'm not committed either way on this table, but everywhere else this applies seems very reasonable!

**Comment by NAretakis** [comment] 2019-03-06 21:22
@jeromeleecms the table above (program budget table) is probably the exception to the rule, because it is formatted with the express purpose of matching our accounting system. Everything else could probably use the new stacked format.

**Comment by hbillings** [comment] 2019-03-06 21:33
Ooh, this looks good! The three tables that are particularly problematic in the print view are this one (`Incentive payments by FFY Quarter`), `Breakout of federal share by quarter` in project activity cost allocation, and the granddaddy `Summary budget table`. Would the summary table make sense stacked? (maybe a question for @jeromeleecms and @NAretakis, as I'm unsure how valuable it is to be able to easily compare across FYs)

**Comment by hbillings** [comment] 2019-03-06 21:47
Hrm, we've also got this bit of functionality in the summary table that I keep forgetting about. I'm really not sure what to do with this in print view. Should it be expanded by default? (It's currently hidden when you print.)
<img width="811" alt="screen shot 2019-03-06 at 2 43 15 pm" src="https://user-images.githubusercontent.com/509309/53916142-a8ff2200-401e-11e9-9f4d-51fd2cfbb59b.png">

**Comment by NAretakis** [comment] 2019-03-06 22:24
@hbillings hidden by default for printing is fine for the summary budget table. For context on longer term thinking, #991 is our icebox issue on what we'd want this functionality to have (at some later date).

**Comment by hbillings** [comment] 2019-03-07 01:20
Screenshot of this here (and you can see it in action in #1358): 
<img width="736" alt="screen shot 2019-03-06 at 6 14 01 pm" src="https://user-images.githubusercontent.com/509309/53925229-68ae9c80-403c-11e9-9d8f-de8f22aaae2c.png">

I just realized I lost the grand total table -- that's something I can get back pretty easily if we want it!

**Closed** 2019-03-18 17:53 UTC
Labels: development
